from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(598, 415)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 571, 391))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(20, 40, 531, 261))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.fileName = QtWidgets.QLineEdit(self.frame)
        self.fileName.setGeometry(QtCore.QRect(80, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fileName.setFont(font)
        self.fileName.setObjectName("fileName")
        self.browsePushButton = QtWidgets.QPushButton(self.frame)
        self.browsePushButton.setGeometry(QtCore.QRect(320, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browsePushButton.setFont(font)
        self.browsePushButton.setObjectName("browsePushButton")
        self.convertPushButton = QtWidgets.QPushButton(self.frame)
        self.convertPushButton.setGeometry(QtCore.QRect(450, 310, 101, 23))
        self.convertPushButton.setObjectName("convertPushButton")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 310, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.languageLabel = QtWidgets.QLabel(self.frame)
        self.languageLabel.setGeometry(QtCore.QRect(30, 330, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.languageLabel.setFont(font)
        self.languageLabel.setObjectName("languageLabel")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(210, 310, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.LanguageComboBox = QtWidgets.QComboBox(self.frame)
        self.LanguageComboBox.setGeometry(QtCore.QRect(210, 330, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LanguageComboBox.setFont(font)
        self.LanguageComboBox.setObjectName("LanguageComboBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "File name"))
        self.browsePushButton.setText(_translate("Dialog", "Browse"))
        self.convertPushButton.setText(_translate("Dialog", "Convert to audio"))
        self.label_2.setText(_translate("Dialog", "Detected language"))
        self.languageLabel.setText(_translate("Dialog", "language"))
        self.label_3.setText(_translate("Dialog", "Select voice"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())